import NextUIContext from "@/contexts/NextUIContext";
import "./globals.css";
import Header from "@/components/Header/Header";
import { globalFont } from "@/utils/fonts/globalFont";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className={`${globalFont.className}`} lang="en">
      <body className="flex flex-col overflow-x-hidden relative ">
        {/* page.js */}
        <main className="grow dark bg-background text-foreground">
          <NextUIContext>{children}</NextUIContext>
        </main>

        {/* footer */}
      </body>
    </html>
  );
}
